trigger:
  batch: true
  branches:
    include:
      - production

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: environment
    value: prd
  - template: templates/variables.yaml

stages:
  - template: templates/deploy-workflow.yaml
