trigger:
  batch: true
  branches:
    include:
      - staging
      - temp/alternative-azure
pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - name: environment
    value: stg
  - template: templates/variables.yaml

stages:
  - template: templates/deploy-workflow.yaml
