FROM python:3.10-slim as poetry-export

WORKDIR /export_staging

# install curl
RUN apt-get update && apt-get install curl -y

# install poetry
RUN curl -sSL https://install.python-poetry.org | python3 -

# copy poetry files
COPY dagster/pyproject.toml dagster/poetry.lock dagster/poetry.toml /export_staging/

# export dependencies into requirements.txt
RUN /root/.local/bin/poetry export -f requirements.txt --output requirements.txt --without-hashes

FROM python:3.10-slim

# install gcc
RUN apt-get update && apt-get install gcc g++ -y

# disable bytecode generation
ENV PYTHONDONTWRITEBYTECODE=1

# allow stdout streams to be sent straight to terminal
ENV PYTHONUNBUFFERED=1

COPY --from=poetry-export /export_staging/requirements.txt .
RUN python3 -m pip install --no-cache-dir -r requirements.txt

# Remove unnecessary stuff to make the image smaller
RUN apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*

# set DAGSTER_HOME, then copy configs and pipeline files into it
ENV DAGSTER_HOME=/opt/dagster/dagster_home
RUN mkdir -p $DAGSTER_HOME
WORKDIR $DAGSTER_HOME

COPY dagster/dagster.yaml $DAGSTER_HOME
COPY dagster/workspace.yaml $DAGSTER_HOME
COPY dagster ./dagster

CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "dagster/src/definitions.py"]
