version: '3'

dotenv:
  - ./dagster/.env
  - ./authproxy/.env

vars:
  PROJECT_NAME: giga-dataops-platform_dagster
  SHORT_SHA:
    sh: git rev-parse --short HEAD

tasks:
  default:
    desc: Build and start Docker containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} up --detach --build --remove-orphans {{.CLI_ARGS}}

  setup:
    desc: Run all first-time setup tasks
    cmds:
      - pip install -U pre-commit
      - pre-commit install
      - task setup-dagster
      - task setup-authproxy

  setup-dagster:
    desc: Run first-time setup tasks for Dagster
    dir: dagster
    cmds:
      - poetry env use 3.11
      - poetry install

  setup-authproxy:
    desc: Run first-time setup tasks for authproxy
    dir: authproxy
    cmds:
      - poetry env use 3.11
      - poetry install

  logs:
    desc: Attach to Docker logs
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} logs --follow {{.CLI_ARGS}}

  stop:
    desc: Stop containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} stop {{.CLI_ARGS}}

  restart:
    desc: Restart containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} restart {{.CLI_ARGS}}

  exec:
    desc: Run a command in the specified container
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} exec {{.CLI_ARGS}}

  clean:
    desc: Remove containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} down --volumes --remove-orphans {{.CLI_ARGS}}

  build-cr:
    desc: Build Docker image
    dir: dagster
    cmds:
      - docker build --tag {{.DAGSTER_IMAGE_REPOSITORY}}:{{.SHORT_SHA}} --no-cache -f Dockerfile.prod .
      - docker build --tag {{.DAGSTER_AUTHPROXY_IMAGE_REPOSITORY}}:{{.SHORT_SHA}} --no-cache -f Dockerfile.prod .

  push-cr:
    desc: Build Docker image
    cmds:
      - docker push {{.DAGSTER_IMAGE_REPOSITORY}}:{{.SHORT_SHA}}
      - docker push {{.DAGSTER_AUTHPROXY_IMAGE_REPOSITORY}}:{{.SHORT_SHA}}

  helm-up:
    desc: Install/upgrade Helm chart
    dir: infra
    cmds:
      - kubectl apply -f k8s/secrets.yaml
      - kubectl apply -f k8s/configmap.yaml
      - |
        helm upgrade --install dagster dagster/dagster \
        --values helm/values.yaml \
        --set dagster-user-deployments.deployments[0].image.repository={{.DAGSTER_IMAGE_REPOSITORY}} \
        --set dagster-user-deployments.deployments[0].image.tag={{.SHORT_SHA}} \
        --set pipelineRun.image.repository={{.DAGSTER_IMAGE_REPOSITORY}} \
        --set pipelineRun.image.tag={{.SHORT_SHA}} \
        --set postgresql.postgresqlUsername={{.POSTGRESQL_USERNAME}} \
        --set postgresql.postgresqlPassword={{.POSTGRESQL_PASSWORD}}

  helm-down:
    desc: Uninstall Helm chart
    dir: infra
    cmds:
      - helm uninstall dagster
      - kubectl delete -f k8s/configmap.yaml
      - kubectl delete -f k8s/secrets.yaml
      - kubectl delete pvc --all
      - kubectl delete pv --all
