version: '3'

dotenv:
  - ./dagster/.env
  - ./oauth2-proxy/.env
  - ./spark/.env
  - ./hive/.env

env:
  SHORT_SHA:
    sh: git rev-parse --short HEAD

vars:
  PROJECT_NAME: giga-dataops_dagster

tasks:
  default:
    cmds:
      - task: up

  up:
    desc: Build and start Docker containers
    cmds:
      - docker compose --project-name giga-dataops-platform --file docker-compose-network.yaml up --detach --build --remove-orphans {{.CLI_ARGS}}
      - docker compose --project-name {{.PROJECT_NAME}} up --detach --build --remove-orphans {{.CLI_ARGS}}

  setup:
    desc: Run all first-time setup tasks
    cmds:
      - task: setup-pre-commit
      - task: setup-helm-repos
      - task: setup-dagster
      - task: setup-authproxy

  setup-pre-commit:
    desc: Run first-time setup tasks for pre-commit
    cmds:
      - pip install -U pre-commit
      - pre-commit install --install-hooks -t pre-commit -t commit-msg

  setup-dagster:
    desc: Run first-time setup tasks for Dagster
    dir: dagster
    cmds:
      - poetry env use 3.11
      - poetry install --with dev,dagster,pipelines,spark,notebook

  setup-authproxy:
    desc: Run first-time setup tasks for authproxy
    dir: authproxy
    cmds:
      - poetry env use 3.11
      - poetry install --with dev

  setup-helm-repos:
    desc: Register all Helm chart repositories
    cmds:
      - helm repo add bitnami https://charts.bitnami.com/bitnami
      - helm repo add dagster https://dagster-io.github.io/helm
      - helm repo update

  logs:
    desc: Attach to Docker logs
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} logs --follow {{.CLI_ARGS}}

  stop:
    desc: Stop containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} stop {{.CLI_ARGS}}

  restart:
    desc: Restart containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} restart {{.CLI_ARGS}}

  exec:
    desc: Run a command in the specified container
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} exec {{.CLI_ARGS}}

  ps:
    desc: Show running processes in this project
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} ps

  clean:
    desc: Remove containers
    cmds:
      - docker compose --project-name {{.PROJECT_NAME}} down --volumes --remove-orphans {{.CLI_ARGS}}

  build-and-push:
    desc: Build and push Docker image
    cmds:
      - task: build
      - task: push

  build:
    desc: Build Docker image
    cmds:
      - docker build --tag {{.DAGSTER_IMAGE_REPOSITORY}}:{{.SHORT_SHA}} -f dagster/prod.Dockerfile dagster
      - docker build --tag {{.DAGSTER_AUTHPROXY_IMAGE_REPOSITORY}}:{{.SHORT_SHA}} -f oauth2-proxy/prod.Dockerfile oauth2-proxy
      - docker build --tag {{.SPARK_IMAGE_REGISTRY}}/{{.SPARK_IMAGE_REPOSITORY}}:{{.SHORT_SHA}} -f spark/prod.Dockerfile .

  push:
    desc: Push Docker image to container registry
    cmds:
      - docker push {{.DAGSTER_IMAGE_REPOSITORY}}:{{.SHORT_SHA}}
      - docker push {{.DAGSTER_AUTHPROXY_IMAGE_REPOSITORY}}:{{.SHORT_SHA}}
      - docker push {{.SPARK_IMAGE_REGISTRY}}/{{.SPARK_IMAGE_REPOSITORY}}:{{.SHORT_SHA}}

  helm-up:
    desc: Install/upgrade Helm charts
    dir: infra
    cmds:
      - kubectl apply -f k8s/namespace.yaml
      - kubectl apply -f k8s/secrets.yaml --namespace giga-dagster
      - kubectl apply -f k8s/configmap.yaml --namespace giga-dagster
      - task: helm-up-dagster
      - task: helm-up-spark
      - task: helm-up-authproxy

  helm-up-dagster:
    desc: Install/upgrade Dagster Helm chart
    dir: infra/helm
    cmds:
      - >
        helm upgrade --install dagster dagster/dagster
        --namespace giga-dagster
        --values dagster/values.yaml
        --set dagster-user-deployments.deployments[0].image.repository={{.DAGSTER_IMAGE_REPOSITORY}}
        --set-string dagster-user-deployments.deployments[0].image.tag={{.SHORT_SHA}}
        --set pipelineRun.image.repository={{.DAGSTER_IMAGE_REPOSITORY}}
        --set pipelineRun.image.tag={{.SHORT_SHA}}
        --set postgresql.postgresqlUsername={{.POSTGRESQL_USERNAME}}
        --set postgresql.postgresqlPassword={{.POSTGRESQL_PASSWORD}}

  helm-up-authproxy:
    desc: Install/upgrade authproxy Helm chart
    dir: infra/helm
    cmds:
      - >
        helm upgrade --install dagster-authproxy ./oauth2-proxy
        --namespace giga-dagster
        --set image.repository={{.DAGSTER_AUTHPROXY_IMAGE_REPOSITORY}}
        --set-string image.tag={{.SHORT_SHA}}
        --set service.type=LoadBalancer
        --set config.clientIdRef.secretRef=giga-dagster-authproxy-secrets
        --set config.clientSecretRef.secretRef=giga-dagster-authproxy-secrets
        --set config.tenantIdRef.secretRef=giga-dagster-authproxy-secrets

  helm-up-spark:
    desc: Install/upgrade Spark Helm chart
    dir: infra/helm
    cmds:
      - >
        helm upgrade --install spark bitnami/spark
        --namespace giga-dagster
        --values spark/values.yaml
        --set image.registry={{.SPARK_IMAGE_REGISTRY}}
        --set image.repository={{.SPARK_IMAGE_REPOSITORY}}
        --set-string image.tag={{.SHORT_SHA}}
        --set service.type=LoadBalancer

  helm-down:
    desc: Uninstall Helm charts
    cmds:
      - helm uninstall dagster-authproxy --namespace giga-dagster
      - helm uninstall spark --namespace giga-dagster
      - helm uninstall dagster --namespace giga-dagster

  helm-clean:
    desc: Clean K8s resources
    dir: infra
    cmds:
      - kubectl delete -f k8s/namespace.yaml

  python:
    desc: >
      Run a Python module inside the Dagster container.
      Usage: `task python -- dotted.path.of.module`
    cmds:
      - task exec -- -it dagster-webserver poetry run python -m {{.CLI_ARGS}}

  ipython:
    desc: Spawn an IPython shell inside the Dagster container
    cmds:
      - task exec -- -it dagster-webserver poetry run ipython
