from src.spark.config_expectations import (
    CONFIG_COLUMNS_EXCEPT_SCHOOL_ID_GEOLOCATION,
    CONFIG_COLUMNS_EXCEPT_SCHOOL_ID_MASTER,
    CONFIG_NONEMPTY_COLUMNS_COVERAGE,
    CONFIG_NONEMPTY_COLUMNS_COVERAGE_FB,
    CONFIG_NONEMPTY_COLUMNS_COVERAGE_ITU,
    CONFIG_NONEMPTY_COLUMNS_GEOLOCATION,
    CONFIG_NONEMPTY_COLUMNS_MASTER,
    CONFIG_NONEMPTY_COLUMNS_REFERENCE,
    CONFIG_UNIQUE_COLUMNS_COVERAGE,
    CONFIG_UNIQUE_COLUMNS_COVERAGE_FB,
    CONFIG_UNIQUE_COLUMNS_COVERAGE_ITU,
    CONFIG_UNIQUE_COLUMNS_GEOLOCATION,
    CONFIG_UNIQUE_COLUMNS_MASTER,
    CONFIG_UNIQUE_COLUMNS_REFERENCE,
    CONFIG_VALUES_DOMAIN_COVERAGE,
    CONFIG_VALUES_DOMAIN_GEOLOCATION,
    CONFIG_VALUES_DOMAIN_MASTER,
    CONFIG_VALUES_DOMAIN_REFERENCE,
    CONFIG_VALUES_RANGE_COVERAGE,
    CONFIG_VALUES_RANGE_COVERAGE_ITU,
    CONFIG_VALUES_RANGE_GEOLOCATION,
    CONFIG_VALUES_RANGE_MASTER,
    CONFIG_VALUES_RANGE_REFERENCE,
)

CONFIG_UNIQUE_COLUMNS = {
    "master": CONFIG_UNIQUE_COLUMNS_MASTER,
    "reference": CONFIG_UNIQUE_COLUMNS_REFERENCE,
    "geolocation": CONFIG_UNIQUE_COLUMNS_GEOLOCATION,
    "coverage": CONFIG_UNIQUE_COLUMNS_COVERAGE,
    "coverage_fb": CONFIG_UNIQUE_COLUMNS_COVERAGE_FB,
    "coverage_itu": CONFIG_UNIQUE_COLUMNS_COVERAGE_ITU,
}
CONFIG_NONEMPTY_COLUMNS = {
    "master": CONFIG_NONEMPTY_COLUMNS_MASTER,
    "reference": CONFIG_NONEMPTY_COLUMNS_REFERENCE,
    "geolocation": CONFIG_NONEMPTY_COLUMNS_GEOLOCATION,
    "coverage": CONFIG_NONEMPTY_COLUMNS_COVERAGE,
    "coverage_fb": CONFIG_NONEMPTY_COLUMNS_COVERAGE_FB,
    "coverage_itu": CONFIG_NONEMPTY_COLUMNS_COVERAGE_ITU,
}
CONFIG_VALUES_DOMAIN = {
    "master": CONFIG_VALUES_DOMAIN_MASTER,
    "reference": CONFIG_VALUES_DOMAIN_REFERENCE,
    "geolocation": CONFIG_VALUES_DOMAIN_GEOLOCATION,
    "coverage": CONFIG_VALUES_DOMAIN_COVERAGE,
}
CONFIG_VALUES_RANGE = {
    "master": CONFIG_VALUES_RANGE_MASTER,
    "reference": CONFIG_VALUES_RANGE_REFERENCE,
    "geolocation": CONFIG_VALUES_RANGE_GEOLOCATION,
    "coverage": CONFIG_VALUES_RANGE_COVERAGE,
    "coverage_itu": CONFIG_VALUES_RANGE_COVERAGE_ITU,
}
CONFIG_COLUMNS_EXCEPT_SCHOOL_ID = {
    "master": CONFIG_COLUMNS_EXCEPT_SCHOOL_ID_MASTER,
    "geolocation": CONFIG_COLUMNS_EXCEPT_SCHOOL_ID_GEOLOCATION,
}
