jobs:
  - deployment: Deploy
    displayName: Delete K8s resources in namespace
    environment: $(kubernetesEnvironment)
    strategy:
      runOnce:
        deploy:
          steps:
            - task: Kubernetes@1
              displayName: Delete resources in namespace
              inputs:
                command: delete
                arguments: all --all
                namespace: $(kubernetesNamespace)

            - task: Kubernetes@1
              displayName: Delete PVCs in namespace
              continueOnError: true
              inputs:
                command: delete
                arguments: pvc --all
                namespace: $(kubernetesNamespace)
