stages:
  - stage: HelmHistory
    displayName: Show Helm history
    dependsOn: [ ]
    jobs:
      - deployment: Deploy
        displayName: Dagster History
        environment: $(kubernetesEnvironment)
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self

                - task: HelmDeploy@0
                  displayName: Check Spark deployment history
                  inputs:
                    command: history
                    chartType: Name
                    releaseName: spark
                    namespace: $(kubernetesNamespace)
                    arguments: spark

                - task: HelmDeploy@0
                  displayName: Check Oauth deployment history
                  inputs:
                    command: history
                    chartType: Name
                    releaseName: dagster-authproxy
                    namespace: $(kubernetesNamespace)
                    arguments: dagster-authproxy
