autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 80
  targetMemory: 80

pdb:
  create: true
  minAvailable: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 192Mi
